const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const bootstrap=fs.readFileSync('tests/ai-commander.cjs','utf8').split('reset();let soldier=')[0];const harness={require,console};vm.createContext(harness);vm.runInContext(bootstrap+';this.fixture={ctx,run,unit,reset};',harness);
const {ctx,run,unit,reset:baseReset}=harness.fixture;
vm.runInContext(fs.readFileSync('js/systems/territory.js','utf8'),ctx);
const T=run('Territory');
const reset=()=>{baseReset();ctx.diplomacy={trust:{},reputation:{},personalities:{},treaties:[],warDeclarations:[],aiMessages:[],diplomaticHistory:[]};ctx.selectedUnit=null;T.reset();run("addAIMessage=(team,message,type)=>diplomacy.aiMessages.push({from:team,message,type});modifyTrust=()=>{};modifyReputation=()=>{};postGameState=()=>{};getActiveTeams=()=>['PLAYER','AI'];getConfiguredTeams=getActiveTeams;resources.PLAYER={gold:100,materials:100};restoreResearchPoints({PLAYER:100,AI:100});");};
reset();const k=unit('Knight',1,1,'PLAYER'),v=unit('Soldier',2,1),v2=unit('Soldier',1,2);v.hp=v2.hp=1;ctx.units=[k,v,v2];assert(ctx.attackUnit(k,v).didKill);assert(!k.hasActed&&k.usedBonusAttack);assert(ctx.attackUnit(k,v2).didKill);assert(k.hasActed);assert(ctx.attackUnit(k,unit('Soldier',2,1)).blocked);
reset();const k2=unit('Knight',1,1,'PLAYER'),healthy=unit('Dragon',2,1);ctx.units=[k2,healthy];ctx.attackUnit(k2,healthy);assert(k2.hasActed);assert(ctx.attackUnit(k2,healthy).blocked,'nonlethal hit cannot earn another attack');
reset();const cat=unit('Catapult',2,2),foe=unit('Soldier',3,2,'PLAYER');ctx.units=[cat,foe];ctx.aiMoveWithGarrison(cat,{col:2,row:3});assert(cat.hasActed);assert(ctx.attackUnit(cat,foe).blocked);cat.hasMoved=cat.hasActed=false;ctx.attackUnit(cat,foe);assert(cat.hasMoved&&cat.hasActed);assert(!ctx.canMoveTo(cat,1,3));
reset();const dragon=unit('Dragon',1,1),target=unit('Catapult',2,1,'PLAYER');ctx.units=[dragon,target];assert.equal(ctx.calculateCombatDamage(dragon,target).damage,80);assert.deepEqual(JSON.parse(JSON.stringify(ctx.getEffectiveUnitCostForTeam('AI','Dragon'))),{gold:3,materials:7});
// Every shown prediction uses precisely the same rounded damage as an actual hit.
for(const at of [null,'WOODS','SWAMP'])for(const hp of [1,30,100])for(const morale of [20,100,140]){
 reset();const a=unit('Swordsman',1,1,'PLAYER'),d=unit('Catapult',2,1);a.hp=Math.min(hp,a.maxHp);a.morale=morale;a.streakBonus=.5;ctx.terrain[13]=at;ctx.units=[a,d];const expected=ctx.calculateCombatDamage(a,d).damage,before=d.hp;ctx.attackUnit(a,d);assert.equal(before-d.hp,Math.min(before,expected));
}
reset();const spear=unit('Spearman',3,3),ally=unit('Spearman',3,2),ally2=unit('Spearman',4,3);ctx.units=[spear,ally];assert.equal(ctx.spearmanDefense(spear),.25);ctx.restoreResearch({AI:['reconnaissance']});assert.equal(ctx.spearmanDefense(spear),.25);ctx.units.push(ally2);assert.equal(ctx.spearmanDefense(spear),.4);ally2.col=7;assert.equal(ctx.spearmanDefense(spear),.25);ally.hp=0;assert.equal(ctx.spearmanDefense(spear),0);
reset();const sword=unit('Swordsman',1,1,'PLAYER');ctx.units=[sword];sword.streakKilled=true;ctx.finishSwordsmanTurn('PLAYER');assert.equal(sword.streakBonus,.4);ctx.finishSwordsmanTurn('PLAYER');assert.equal(sword.streakBonus,.4,'no duplicate advancement');for(let i=2;i<=9;i++){ctx.turnNumber=i;sword.streakKilled=true;ctx.finishSwordsmanTurn('PLAYER');}assert.equal(sword.streakBonus,1);ctx.turnNumber++;ctx.finishSwordsmanTurn('PLAYER');assert.equal(sword.streakBonus,.5);const copy=ctx.makeUnit(sword.name,sword.team,sword.col,sword.row,JSON.parse(JSON.stringify(sword)));ctx.units=[copy];ctx.turnNumber++;ctx.finishSwordsmanTurn('PLAYER');assert.equal(copy.streakBonus,0);ctx.turnNumber++;copy.streakKilled=true;ctx.finishSwordsmanTurn('PLAYER');assert.equal(copy.streakBonus,.4);
reset();ctx.restoreResearch({PLAYER:['rapid_mobilization']});const recruit=ctx.makeUnit('Soldier','PLAYER',1,1,{justSpawned:true});ctx.units=[recruit];assert.equal(recruit.spawnMoveLimit,1);assert(!recruit.hasMoved&&recruit.hasActed);assert(ctx.canMoveTo(recruit,2,1));assert(!ctx.canMoveTo(recruit,3,1));const newCat=ctx.makeUnit('Catapult','PLAYER',5,5,{justSpawned:true});assert(newCat.hasMoved&&newCat.hasActed);ctx.restoreResearch({PLAYER:['rapid_mobilization','siege_mobility']});const mobileCat=ctx.makeUnit('Catapult','PLAYER',5,5,{justSpawned:true});ctx.units=[mobileCat];assert(ctx.canMoveTo(mobileCat,5,6));assert(ctx.attackUnit(mobileCat,unit('Soldier',5,6)).blocked);
assert.equal(run("RESEARCH_TREE.dragon_corps.branch"),'command');assert.equal(run("RESEARCH_TREE.mass_production.name"),'Recycling');assert.equal(run("RESEARCH_TREE.rapid_mobilization.name"),'Mass Production');assert.equal(run("RESEARCH_TREE.reconnaissance.name"),'Phalanx Warriors');
reset();ctx.units=[unit('Soldier',1,1)];for(const terrain of [null,'GRASS','FARM','DESERT','WOODS','MOUNTAIN','FOUNTAIN','BRIDGE']){ctx.terrain[14]=terrain;assert(ctx.canBuildFortressAt('AI',2,1),terrain);}for(const terrain of ['SWAMP','MARSH','WATER','VOID']){ctx.terrain[14]=terrain;assert(!ctx.canBuildFortressAt('AI',2,1),terrain);}
reset();ctx.units=[unit('Soldier',1,1,'PLAYER')];T.restore({cols:12,rows:8,claims:Array(96).fill('AI')});ctx.refreshEliminatedNations();assert(ctx.isNationEliminated('AI'));assert(!T.ownership().includes('AI'));const eliminated=ctx.diplomacy.eliminatedNations.AI;ctx.refreshEliminatedNations();assert.equal(ctx.diplomacy.eliminatedNations.AI,eliminated);
// Both crusade triggers, strength guard, exact five-turn window and no repeated notice.
for(const mode of ['kills','turns']){
 reset();const human=unit('Soldier',8,5,'PLAYER'),ai=unit('Dragon',1,1);ctx.units=[human,ai];ctx.updateCrusade('AI');human.dmg+=1;
 for(let t=1;t<=5;t++){ctx.turnNumber=t;ctx.recordCrusadeCombat(human,ai,mode==='kills');}ctx.updateCrusade('AI');assert(ctx.isCrusading('AI'));assert.equal(ctx.diplomacy.aiMessages.filter(m=>m.type==='CRUSADE').length,1);
 for(let t=6;t<=9;t++){ctx.turnNumber=t;ctx.updateCrusade('AI');assert(ctx.isCrusading('AI'));}ctx.turnNumber=10;ctx.updateCrusade('AI');assert(!ctx.isCrusading('AI'));assert.equal(ctx.diplomacy.aiMessages.length,1);
}
reset();const human=unit('Dragon',8,5,'PLAYER'),weak=unit('Soldier',1,1);ctx.units=[human,weak];ctx.updateCrusade('AI');human.dmg++;ctx.turnNumber=2;for(let i=0;i<5;i++)ctx.recordCrusadeCombat(human,weak,true);ctx.updateCrusade('AI');assert(!ctx.isCrusading('AI'));
for(const pool of Object.values(run('DIPLOMACY_PHRASES')))assert.equal(new Set(pool).size,20);
const callbacks=[];ctx.setTimeout=fn=>callbacks.push(fn);ctx.scheduleDiplomacy(()=>{throw Error('stale diplomacy callback');},100);ctx.diplomacy.peaceBeggingFlags={AI:20};ctx.resetDiplomacySession();callbacks.forEach(fn=>fn());assert(!ctx.diplomacy.peaceBeggingFlags);assert.deepEqual(JSON.parse(JSON.stringify(run('messageHistory'))),{});
console.log('Knight follow-up, siege action exclusivity, exact combat previews, Phalanx, streak lifecycle, deployment movement, construction, elimination, crusades and session reset pass.');
