const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c={console,clearTimeout,ActionEffects:{reset(){}},closeSpawnMenu(){},buildMode:true,buildModeUnitId:'old',activeAITurn:{},aiTurnTimeoutId:null,BOARD_SIZE:600,mapSize:{cols:3,rows:3},maxAIPlayers:4,currentAIPlayers:1,resources:{PLAYER:{gold:17,materials:4},AI:{gold:12,materials:2}},startingResources:{PLAYER:{gold:17,materials:4},AI:{gold:12,materials:2}},researchedUnits:{PLAYER:new Set(['Soldier','Archer']),AI:new Set(['Soldier'])},terrain:Array(9).fill(null),settlements:Array(9).fill(null),units:[],diplomacy:{},currentVictoryCondition:{type:'ANNIHILATE_ALL'},getActiveTeams:()=>['PLAYER','AI'],readVictoryConditionFromUI(){},hasAIDiplomacy:()=>false,updateHexSize(){},resizeGameCanvas(){},select:()=>null,setAIPlayerCount(){},document:{getElementById:()=>null},calculateTurnOrder(){},updateTeamSelector(){},hideEndScreen(){},updateUI(){},selectedUnit:null,gameOver:false,endScreenShown:false,gameEndResult:null,currentTeam:'PLAYER',currentTurnIndex:0,turnNumber:1,activeScenarioSnapshot:null,campaignMode:{active:false},lastPlayedSavedLevelIndex:null,setupGame(){throw Error('Must not use default Knights');}};
vm.createContext(c);
for(const f of ['js/systems/economy-research.js','js/data/units-and-build.js','js/core/level-state.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);
vm.runInContext('resources={PLAYER:{gold:17,materials:4},AI:{gold:12,materials:2}};researchedUnits={PLAYER:new Set(["Soldier","Archer"]),AI:new Set(["Soldier"])};',c);
Object.defineProperty(c,'resources',{get:()=>vm.runInContext('resources',c)});
Object.defineProperty(c,'researchedUnits',{get:()=>vm.runInContext('researchedUnits',c)});
c.closeSpawnMenu=()=>{};c.normalizeVictoryCondition=x=>structuredClone(x);c.applyVictoryConditionToUI=()=>{};
vm.runInContext(fs.readFileSync('js/ui/endgame-and-ui.js','utf8').match(/function replayCurrentScenario\(\) \{[\s\S]*?\n\}/)[0],c);
c.units=[c.makeUnit('Archer','PLAYER',0,0,{id:'archer'}),c.makeUnit('Dragon','AI',2,2,{id:'dragon'})];c.settlements[0]={owner:'PLAYER',type:'CITY'};c.terrain[4]='WOODS';c.captureScenarioSnapshot();const original=JSON.stringify(c.activeScenarioSnapshot);
for(let attempt=0;attempt<2;attempt++){
 c.units[0].hp=1;c.units.push(c.makeUnit('Soldier','PLAYER',1,1));c.resources.PLAYER.gold=0;c.resources.AI.materials=99;c.researchedUnits.PLAYER.add('Dragon');c.settlements[0].owner='AI';c.terrain[4]='WATER';c.currentTeam='AI';c.turnNumber=7;c.activeAITurn={};
 c.replayCurrentScenario();assert.equal(c.units.length,2);assert.equal(c.units[0].name,'Archer');assert.equal(c.units[0].hp,50);assert.equal(c.resources.PLAYER.gold,0);assert.equal(c.resources.AI.materials,0);assert(!c.researchedUnits.PLAYER.has('Dragon'));assert(c.researchedUnits.PLAYER.has('Archer'));assert.equal(c.settlements[0].owner,'PLAYER');assert.equal(c.terrain[4],'WOODS');assert.equal(c.currentTeam,'PLAYER');assert.equal(c.turnNumber,1);assert.equal(c.activeAITurn,null);assert.equal(JSON.stringify(c.activeScenarioSnapshot),original,'restarts do not mutate original snapshot');
}
const legacy=structuredClone(c.activeScenarioSnapshot);delete legacy.resources;delete legacy.research;c.applyLevelData(legacy);assert.equal(c.resources.PLAYER.gold,0);assert.deepEqual([...c.researchedUnits.PLAYER],['Soldier']);
console.log('Repeated scenario restarts restore armies, health, ownership, terrain, resources, research and turn state; legacy levels also start with zero balances.');
