// Manual browser fixture: loads the production scripts, then provides explicit
// test controls. This file is never included by the shipped game page.
window.addEventListener('load',()=>{
 const bar=document.createElement('nav');bar.id='testControls';bar.style.cssText='position:fixed;left:240px;bottom:0;z-index:40000;display:flex;background:#101822;padding:5px;gap:5px';document.body.appendChild(bar);
 function base(){BattleGuide.dismiss();watchGameMode=false;watchGamePaused=false;isEditorMode=false;gameOver=false;endScreenShown=false;campaignMode.active=false;opponentType='AI';currentAIPlayers=4;aiTeamNames=['AI','AI2','AI3','AI4'];maxAIPlayers=4;resetDiplomacySession();initializeDiplomacy();resetResearch(getActiveTeams());mapSize={cols:14,rows:12};COLS=14;ROWS=12;TILE=BOARD_SIZE/COLS;terrain=Array(COLS*ROWS).fill(null);settlements=Array(COLS*ROWS).fill(null);units=[];Territory.reset();turnNumber=1;currentTeam='PLAYER';selectedUnit=null;currentVictoryCondition={...DEFAULT_VICTORY_CONDITION};closeSpawnMenu();document.getElementById('mainMenu').classList.add('hidden');hideEndScreen();updateHexSize();resizeGameCanvas();calculateTurnOrder();for(const t of getActiveTeams())resources[t]={gold:100,materials:100};restoreResearchPoints({PLAYER:100});}
 function add(label,action){const b=document.createElement('button');b.textContent=label;b.onclick=action;bar.appendChild(b);}
 add('Art gallery',()=>{
  base();document.getElementById('testGallery')?.remove();const pane=document.createElement('div');pane.id='testGallery';pane.style.cssText='position:fixed;inset:0;z-index:30000;overflow:auto;background:#111c28;padding:30px 30px 65px;color:#fff';
  pane.innerHTML='<h1>All unit types × five nations</h1><button id="galleryClose">Close gallery</button><select id="galleryUnit" aria-label="Artwork unit"><option value="">All units</option>'+Object.keys(UNIT_TEMPLATES).map(n=>`<option>${n}</option>`).join('')+'</select><div style="display:grid;grid-template-columns:repeat(5,minmax(140px,1fr));gap:8px"></div>';document.body.appendChild(pane);pane.querySelector('button').onclick=()=>pane.remove();const grid=pane.querySelector('div');
  for(const name of Object.keys(UNIT_TEMPLATES))for(const [i,team]of getConfiguredTeams().entries()){const u=makeUnit(name,team,i,1,{id:name.replace(/\W/g,'')+team});units.push(u);const cell=document.createElement('article');cell.dataset.unit=name;cell.style.cssText='text-align:center;border:1px solid #45515e;border-radius:8px;padding:8px';cell.innerHTML=UnitPresentation.preview(u)+`<strong>${name} · ${getTeamDisplayName(team)}</strong>`;grid.appendChild(cell);}
  pane.querySelector('select').onchange=e=>{for(const cell of grid.children)cell.hidden=!!e.target.value&&cell.dataset.unit!==e.target.value;pane.scrollTop=0;};
  const neutralArt=new Set(['Swordsman','Assassin','Dragon']);
  const results=[];for(const name of Object.keys(UNIT_TEMPLATES)){const fingerprints=new Set();for(const u of units.filter(u=>u.name===name)){const sprite=UnitPresentation.sprite(u);if(sprite?.getContext)fingerprints.add(sprite.toDataURL());}results.push({name,variants:fingerprints.size,expected:neutralArt.has(name)?1:5});}
  const result=document.createElement('p');result.textContent=results.every(r=>r.variants===r.expected)?`PASS: ${results.length-neutralArt.size} unit types × 5 nation sprites plus ${neutralArt.size} neutral elite silhouettes.`:'FAIL: '+JSON.stringify(results.filter(r=>r.variants!==r.expected));pane.prepend(result);
  updateUI();
 });
 add('Combat / effects',()=>{base();settlements[10*COLS+2]={type:'CITY',owner:'PLAYER'};settlements[10*COLS+11]={type:'CITY',owner:'AI'};const addU=(n,t,c,r,opts={})=>{const u=makeUnit(n,t,c,r,opts);units.push(u);return u;};restoreResearch({PLAYER:['reconnaissance','longbows']});addU('Spearman','PLAYER',4,4);addU('Spearman','PLAYER',3,4);addU('Spearman','PLAYER',4,3);addU('Swordsman','PLAYER',3,7,{streakBonus:.7});addU('Swordsman','PLAYER',6,7,{streakBonus:.4});addU('Soldier','PLAYER',2,5,{morale:0});addU('Archer','PLAYER',7,4);addU('Catapult','PLAYER',7,7);addU('Dragon','AI',9,6);addU('Soldier','AI',8,4);addU('Knight','PLAYER',3,2);addU('Soldier','AI',4,2,{hp:1});addU('Soldier','AI',3,1,{hp:1});updateUI();});
 add('Diplomacy / treaties',()=>{base();for(const [i,t]of getConfiguredTeams().entries()){units.push(makeUnit('Soldier',t,i*2,2));settlements[8*COLS+i*2]={type:'CITY',owner:t};}for(const t of ['PLAYER','AI2','AI3','AI4'])createTreaty('AI',t,'DEFENSIVE_PACT');for(let i=0;i<150;i++)addAIMessage('AI','A message','UNIT_KILLED');diplomacy.peaceBeggingFlags={AI:6};updateUI();openDiplomacyNegotiation();selectDiplomacyTarget('AI');});
 add('Eliminate AI',()=>{units=units.filter(u=>u.team!=='AI');settlements=settlements.map(s=>s?.owner==='AI'?{...s,owner:'PLAYER'}:s);refreshEliminatedNations();updateUI();openDiplomacyNegotiation();});
 add('Research',()=>{base();units=[makeUnit('Soldier','PLAYER',2,2),makeUnit('Soldier','AI',11,9)];settlements[2*COLS+2]={type:'CITY',owner:'PLAYER'};settlements[9*COLS+11]={type:'CITY',owner:'AI'};updateUI();openSpawnMenu(2,2,settlements[2*COLS+2],'research');});
});
